account: 
  # en: https://leetcode.com
  # cn: https://leetcode-cn.com
  # en | cn
  domain: en
  # username | email
  user: your_username_or_email
  # your leetcode password
  password: your_password

repo: 
  # your git repo remote url, like this:
  - git@github.com:username/leetcode.git
